name: 'Android  Report Action'
description: 'GitHub Action that prints Android test and Unit test reports'
author: 'DoanPT'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'file-text'
  color: 'red'
